"""Response execution services (Phase 3.1).

The controlled-execution layer on top of approved recommendations:
Approval -> Execute Intent -> Guard -> execution_log -> Executor.
3.1.3 delivered the state semantics, 3.1.4 the Guard / Policy verdicts,
3.1.5 the executor contract + Mock/DryRun adapter + registry, 3.1.6 the
Execute / Compensation Service that wires them into complete chains.
No API here yet.
"""

from app.services.executions.base import ResponseExecutor
from app.services.executions.exceptions import (
    ExecutorConfigError,
    ExecutorError,
    ExecutorOutcomeViolation,
)
from app.services.executions.guard import (
    EXECUTABLE_ACTIONS,
    GUARD_REJECTION_CODES,
    NON_COMPENSATABLE_ACTIONS,
    ApprovalAlreadyExecuted,
    ApprovalNotFound,
    ExecutionGuardError,
    ExecutionIdAlreadyBound,
    ExecutorCapability,
    GuardRejection,
    check_approval_binding,
    check_executor_capability,
    check_lifecycle,
)
from app.services.executions.mock import FAIL_WITH_CHOICES, MockExecutor
from app.services.executions.models import (
    ADAPTER_CLASSIFICATIONS,
    FAILURE_CLASSIFICATIONS,
    OUTCOME_STATUSES,
    ExecutionDispatch,
    ExecutionOutcome,
)
from app.services.executions.health import (
    DEFAULT_THRESHOLDS,
    DEFAULT_WINDOW_SIZE,
    OBSERVED_STATUSES,
    AdapterHealth,
    HealthThresholds,
    ObservedHealth,
    RecentFailure,
    collect_observed_health,
)
from app.services.executions.metrics import (
    UNKNOWN_ADAPTER,
    AdapterMetrics,
    ExecutionMetrics,
    LatencyStats,
    collect_execution_metrics,
)
from app.services.executions.operators import (
    LEGACY_OPERATOR_NAME,
    Operator,
    OperatorRegistry,
    OperatorRole,
    VALID_ROLES,
    build_registry,
    get_operator_registry,
    reset_operator_registry,
)
from app.services.executions.policy import (
    ALLOW,
    DEFAULT_MIN_RISK_BY_ACTION,
    POLICY_REJECTION_CODES,
    POLICY_SOURCE,
    ExecutionPolicy,
    PolicyContext,
    PolicyDecision,
    PolicyViolation,
    evaluate_execution_policy,
    parse_hhmm,
    policy_from_settings,
)
from app.services.executions.protocol import parse_execution_outcome
from app.services.executions.registry import (
    ADAPTER_NAMES,
    ADAPTER_REQUIRED_SETTINGS,
    KNOWN_ADAPTER_NAMES,
    RECOGNIZED_ADAPTER_NAMES,
    RESERVED_ADAPTER_NAMES,
    create_executor,
    validate_adapter_config,
)
from app.services.executions.secrets import (
    MASK,
    AdapterCredentials,
    SecretRedactionFilter,
    credentials_from_settings,
    current_secret_values,
    redact_detail,
    redact_text,
    validate_api_key,
    validate_base_url,
)
from app.services.executions.service import (
    COMPENSATABLE_STATES,
    ApprovalAlreadyExecuted,
    CompensationOfCompensation,
    ExecutionAlreadyCompensated,
    ExecutionConflictError,
    ExecutionIdAlreadyBound,
    ExecutionNotFound,
    ExecutionResult,
    ExecutionServiceError,
    OriginalExecutionNotTerminal,
    compensate_response,
    execute_response,
)
from app.services.executions.shuffle import (
    SHUFFLE_ACTIONS,
    SHUFFLE_REVERSE_WORKFLOW_SETTINGS,
    SHUFFLE_WORKFLOW_SETTINGS,
    ShuffleExecutor,
    reverse_workflow_map_from_settings,
    workflow_map_from_settings,
)
from app.services.executions.state import (
    ALLOWED_TRANSITIONS,
    DIRECTION_VOCABULARY,
    FIRST_ROW_BY_DIRECTION,
    TERMINAL_DECISIONS,
    ExecutionDirectionMismatch,
    ExecutionLogRow,
    ExecutionStateError,
    InvalidExecutionTransition,
    derive_execution_state,
    is_terminal_state,
    validate_transition,
)
from app.services.executions.thehive import (
    THEHIVE_ACTIONS,
    TheHiveExecutor,
)
from app.services.executions.wazuh import (
    WAZUH_ACTIONS,
    WAZUH_COMMANDS,
    WAZUH_REVERSE_COMMANDS,
    WazuhExecutor,
)

__all__ = [
    "ADAPTER_CLASSIFICATIONS",
    "ADAPTER_NAMES",
    "ADAPTER_REQUIRED_SETTINGS",
    "ALLOW",
    "ALLOWED_TRANSITIONS",
    "COMPENSATABLE_STATES",
    "DEFAULT_MIN_RISK_BY_ACTION",
    "DEFAULT_THRESHOLDS",
    "DEFAULT_WINDOW_SIZE",
    "DIRECTION_VOCABULARY",
    "EXECUTABLE_ACTIONS",
    "FAILURE_CLASSIFICATIONS",
    "FAIL_WITH_CHOICES",
    "FIRST_ROW_BY_DIRECTION",
    "GUARD_REJECTION_CODES",
    "KNOWN_ADAPTER_NAMES",
    "LEGACY_OPERATOR_NAME",
    "MASK",
    "NON_COMPENSATABLE_ACTIONS",
    "OBSERVED_STATUSES",
    "OUTCOME_STATUSES",
    "POLICY_REJECTION_CODES",
    "POLICY_SOURCE",
    "RECOGNIZED_ADAPTER_NAMES",
    "RESERVED_ADAPTER_NAMES",
    "SHUFFLE_ACTIONS",
    "SHUFFLE_REVERSE_WORKFLOW_SETTINGS",
    "SHUFFLE_WORKFLOW_SETTINGS",
    "TERMINAL_DECISIONS",
    "THEHIVE_ACTIONS",
    "UNKNOWN_ADAPTER",
    "WAZUH_ACTIONS",
    "WAZUH_COMMANDS",
    "WAZUH_REVERSE_COMMANDS",
    "AdapterCredentials",
    "AdapterHealth",
    "AdapterMetrics",
    "ApprovalAlreadyExecuted",
    "ApprovalNotFound",
    "Operator",
    "OperatorRegistry",
    "OperatorRole",
    "CompensationOfCompensation",
    "ExecutionAlreadyCompensated",
    "ExecutionConflictError",
    "ExecutionDirectionMismatch",
    "ExecutionDispatch",
    "ExecutionGuardError",
    "ExecutionIdAlreadyBound",
    "ExecutionLogRow",
    "ExecutionMetrics",
    "ExecutionNotFound",
    "ExecutionOutcome",
    "ExecutionPolicy",
    "ObservedHealth",
    "ExecutionResult",
    "ExecutionServiceError",
    "ExecutionStateError",
    "ExecutorCapability",
    "ExecutorConfigError",
    "ExecutorError",
    "ExecutorOutcomeViolation",
    "GuardRejection",
    "HealthThresholds",
    "InvalidExecutionTransition",
    "LatencyStats",
    "MockExecutor",
    "OriginalExecutionNotTerminal",
    "PolicyContext",
    "PolicyDecision",
    "RecentFailure",
    "PolicyViolation",
    "ResponseExecutor",
    "SecretRedactionFilter",
    "ShuffleExecutor",
    "TheHiveExecutor",
    "WazuhExecutor",
    "build_registry",
    "check_approval_binding",
    "check_executor_capability",
    "check_lifecycle",
    "collect_execution_metrics",
    "collect_observed_health",
    "compensate_response",
    "create_executor",
    "credentials_from_settings",
    "current_secret_values",
    "derive_execution_state",
    "evaluate_execution_policy",
    "execute_response",
    "get_operator_registry",
    "is_terminal_state",
    "parse_execution_outcome",
    "parse_hhmm",
    "policy_from_settings",
    "redact_detail",
    "redact_text",
    "reset_operator_registry",
    "reverse_workflow_map_from_settings",
    "validate_adapter_config",
    "validate_api_key",
    "validate_base_url",
    "validate_transition",
    "VALID_ROLES",
    "workflow_map_from_settings",
]
